const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const code = fs.readFileSync(path.join(__dirname, "..", "app.js"), "utf8");
const source = code.slice(code.indexOf("function smoothImportedMeshMaterial("), code.indexOf("function relaxSurfaceGeometry("));
const context = { THREE: { FrontSide: 0 } };
vm.createContext(context);
vm.runInContext(source, context);
const faceted = { userData: { facetedGem: true }, flatShading: false };
const smooth = { userData: { facetedGem: false }, flatShading: true };
context.smoothImportedMeshMaterial({ material: [faceted, smooth], geometry: { getAttribute: () => null } });
assert.equal(faceted.flatShading, true);
assert.equal(smooth.flatShading, false);
assert.equal(faceted.needsUpdate, true);
assert(code.includes("material.userData.facetedGem = !optical.isCabochon && !optical.isPearl;"));
const pipeline = code.slice(code.indexOf("function applyImportedMeshProcessing("), code.indexOf("function smoothImportedMeshMaterial("));
assert(pipeline.indexOf('classicPlugRole === "gem"') < pipeline.indexOf("if (processing.weldTolerance"));
assert(pipeline.includes("child.geometry = original.toNonIndexed();"));
assert(pipeline.includes("child.geometry.computeVertexNormals();"));
const normalize = code.slice(code.indexOf("function normalizeImportedModel("), code.indexOf("function applyImportedMeshProcessing("));
assert(normalize.indexOf("assignClassicPlugMaterialsByVolume(model, meshOptions)") < normalize.indexOf("applyImportedMeshProcessing(model, meshOptions)"));
console.log("Faceted gems: OK");
