const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const source = fs.readFileSync(require("node:path").join(__dirname, "../welcome.js"), "utf8");
const start = source.indexOf("function acceptPromptSuggestion");
const end = source.indexOf("const bronzePreviewCache", start);
const context = { Event: class { constructor(type, options) { this.type = type; this.bubbles = options.bubbles; } } };
vm.runInNewContext(source.slice(start, end), context);
let prevented = false;
const event = { key: "Tab", preventDefault() { prevented = true; } };
const field = { value: "", placeholder: "Exemple : un plug MEDIUM inox", setSelectionRange(a,b) { this.selection = [a,b]; }, dispatchEvent(e) { this.event = e; } };
context.acceptPromptSuggestion(event, field);
assert.equal(field.value, "un plug MEDIUM inox");
assert(prevented);
assert.deepEqual(field.selection, [field.value.length, field.value.length]);
assert.equal(field.event.type, "input");
field.value = "Mon choix personnel";
prevented = false;
context.acceptPromptSuggestion(event, field);
assert.equal(field.value, "Mon choix personnel");
assert.equal(prevented, false);
field.value = "";
context.acceptPromptSuggestion({ ...event, shiftKey: true }, field);
assert.equal(field.value, "");
assert.equal(prevented, false);
console.log("Tab insere la suggestion editable sans ecraser un texte existant OK");
